import { StyleSheet } from 'react-native';

export const eventCardStyles = StyleSheet.create({
  swipeContainer: {
    position: 'relative',
    marginBottom: 12,
    overflow: 'visible', // Позволяем аватарке организатора выходить за пределы
  },
  swipeButtonContainer: {
    position: 'absolute',
    right: 16,
    top: '50%',
    transform: [{ translateY: -30 }],
    zIndex: 1,
    alignItems: 'center',
  },
  swipeButtonContainerWithSecondary: {
    transform: [{ translateY: -60 }], // Смещаем вверх, если две кнопки
  },
  swipeButton: {
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    marginBottom: 10, // Отступ между кнопками
  },
  swipeButtonSecondary: {
    marginBottom: 0, // Для нижней кнопки отступ не нужен
  },
  swipeButtonIcon: {
    color: '#f4f4f5',
    fontSize: 20,
    fontWeight: 'bold',
  },
  swipeButtonLabel: {
    color: '#f4f4f5',
    fontSize: 10,
    fontWeight: '600',
    marginTop: 2,
    textAlign: 'center',
  },
  goButtonContainer: {
    position: 'absolute',
    right: 16,
    top: '50%',
    transform: [{ translateY: -30 }],
    zIndex: 1,
  },
  goButton: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#FF8D32',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#FF8D32',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  goButtonText: {
    color: '#0A0A0A',
    fontSize: 16,
    fontWeight: 'bold',
  },
  card: {
    backgroundColor: '#16161a',
    borderRadius: 28,
    padding: 0,
    marginBottom: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.32,
    shadowRadius: 28,
    elevation: 4,
    position: 'relative',
    overflow: 'hidden',
  },
  /** Аватар организатора — как раньше, снаружи карточки (относительно swipeContainer) */
  organizerAvatarContainer: {
    position: 'absolute',
    top: -14,
    right: -10,
    zIndex: 10,
  },
  organizerAvatar: {
    width: 64,
    height: 64,
    borderRadius: 22,
    borderWidth: 2.5,
    borderColor: '#16161a',
    backgroundColor: '#3a3a3f',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 6,
  },
  horizontalLayout: {
    flexDirection: 'row',
    paddingTop: 40,
    paddingBottom: 15,
    paddingLeft: 140, // Отступ для фото слева
    position: 'relative',
  },
  verticalLayout: {
    flexDirection: 'column',
    width: '100%',
    alignSelf: 'stretch',
    paddingTop: 0,
    paddingBottom: 15,
    position: 'relative',
  },
  mediaContainerHorizontal: {
    width: 120,
    height: '100%',
    marginRight: 12,
    borderRadius: 0,
    overflow: 'hidden',
    borderTopLeftRadius: 12,
    borderBottomLeftRadius: 12,
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
  },
  mediaContainerVertical: {
    width: '100%',
    alignSelf: 'stretch',
    height: 220,
    marginBottom: 0,
    borderRadius: 0,
    overflow: 'hidden',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
  },
  mediaImageHorizontal: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  mediaImageVertical: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  contentContainer: {
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 16,
    paddingBottom: 14,
  },
  title: {
    fontSize: 19,
    fontWeight: '700',
    color: '#f4f4f5',
    marginBottom: 7,
    letterSpacing: -0.3,
    lineHeight: 24,
  },
  description: {
    fontSize: 14.5,
    color: 'rgba(244,244,245,0.62)',
    lineHeight: 21,
    marginBottom: 10,
  },
  descriptionToggle: {
    fontSize: 12.5,
    color: '#FF8D32',
    fontWeight: '600',
    alignSelf: 'flex-start',
  },
  parametersContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 10,
    gap: 7,
  },
  parameterItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.045)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    paddingHorizontal: 11,
    paddingVertical: 6,
    borderRadius: 14,
    marginRight: 0,
    marginBottom: 0,
    minWidth: 0,
    maxWidth: '100%',
  },
  parameterEmoji: {
    fontSize: 12.5,
    marginRight: 5,
  },
  parameterText: {
    fontSize: 12.5,
    color: 'rgba(244,244,245,0.78)',
    fontWeight: '600',
    flexShrink: 1,
    minWidth: 0,
  },
  participantsAvatars: {
    flexDirection: 'row',
    marginTop: 8,
    flexWrap: 'wrap',
  },
  participantAvatar: {
    width: 24,
    height: 24,
    borderRadius: 12,
    marginRight: 4,
    marginBottom: 4,
  },
  participantAvatarContainer: {
    alignItems: 'center',
    marginRight: 8,
    marginBottom: 8,
  },
  participantName: {
    fontSize: 10,
    color: 'rgba(244,244,245,0.55)',
    marginTop: 2,
    textAlign: 'center',
    maxWidth: 60,
  },
  moreParticipants: {
    fontSize: 12,
    color: 'rgba(244,244,245,0.55)',
    alignSelf: 'center',
    marginLeft: 4,
  },
  // Стили для мини-аватаров участников в параметрах
  participantsParameterItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2a2a2a',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    marginRight: 6,
    marginBottom: 4,
  },
  participantsMiniAvatars: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 6,
  },
  participantMiniAvatar: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 0.5,
    borderColor: 'rgba(255,255,255,0.15)',
  },
  participantMoreMini: {
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  participantMoreMiniText: {
    color: '#f4f4f5',
    fontSize: 8,
    fontWeight: 'bold',
  },
  participantsCountText: {
    fontSize: 12,
    color: '#DDDDDD',
    fontWeight: '500',
  },
  playButton: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: [{ translateX: -20 }, { translateY: -20 }],
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    borderRadius: 25,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  playIcon: {
    fontSize: 16,
    color: '#f4f4f5',
  },
  // Миниатюрные варианты для профилей
  miniatureCard1: {
    width: '100%', // Ширина задается динамически через родительский View
    height: 110, // Фиксированная высота
    borderRadius: 12,
    overflow: 'visible', // Изменяем на visible для больших аватарок
    position: 'relative',
    backgroundColor: '#2a2a2a',
    marginBottom: 10,
    marginTop: 5,
  },
  miniatureCard2: {
    width: 100, // Уменьшил с 140 до 100 для трех колонок
    height: 100, // Уменьшил с 140 до 100 для трех колонок
    borderRadius: 12,
    overflow: 'visible', // Изменяем на visible для больших аватарок
    position: 'relative',
    backgroundColor: '#2a2a2a',
    marginBottom: 10,
    marginTop: 5,
  },
  chatPreview: {
    width: '100%',
    minWidth: 200,
    height: 100,
    minHeight: 100,
    borderRadius: 12,
    overflow: 'hidden',
    position: 'relative',
    backgroundColor: '#2a2a2a',
    borderWidth: 1,
    borderColor: '#3a3a3a',
  },
  chatPreviewTitleContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
  },
  chatPreviewTitle: {
    color: '#f4f4f5',
    fontSize: 14,
    fontWeight: '600',
  },
  // Стили для фонового изображения мини-карточки
  miniatureBackgroundContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 12, // Скругление углов как у карточки
    overflow: 'hidden', // Обрезаем содержимое по скругленным углам
  },
  miniatureBackgroundImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
    borderRadius: 12, // Скругление углов изображения
  },
  miniatureOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    borderRadius: 12, // Скругление углов как у карточки
  },
  miniaturePlayButton: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: [{ translateX: -15 }, { translateY: -15 }],
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    borderRadius: 20,
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  miniaturePlayIcon: {
    fontSize: 12,
    color: '#f4f4f5',
  },
  // Аватарка организатора для мини-карточки
  miniatureOrganizerAvatarContainer: {
    position: 'absolute',
    top: -8, // Слегка выходим за пределы мини-карточки вверх
    right: -8, // Слегка выходим за пределы мини-карточки вправо
    zIndex: 10,
  },
  miniatureOrganizerAvatarFrame: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.85)',
    backgroundColor: 'rgba(0, 0, 0, 0.25)',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 4,
  },
  miniatureOrganizerAvatar: {
    width: 32, // Уменьшил с 48 до 32 пропорционально
    height: 32,
    borderRadius: 16,
    backgroundColor: 'transparent',
  },
  // Участники для мини-карточки
  miniatureParticipantsContainer: {
    position: 'absolute',
    bottom: 8,
    right: 8,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 10,
  },
  miniatureParticipantAvatar: {
    width: 18, // Одинаковый размер с обычной карточкой
    height: 18,
    borderRadius: 9,
    borderWidth: 0.5, // Более тонкая обводка
    borderColor: 'rgba(255,255,255,0.15)',
  },
  miniatureMoreParticipants: {
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  miniatureMoreText: {
    color: '#f4f4f5',
    fontSize: 8, // Меньший шрифт для "+n" на мини-карточке
    fontWeight: 'bold',
  },
  // Метка "Вас пригласили"
  invitedLabel: {
    position: 'absolute',
    top: 8,
    left: 8,
    backgroundColor: '#FF8D32',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    zIndex: 20,
  },
  invitedLabelText: {
    color: '#0A0A0A',
    fontSize: 11,
    fontWeight: '600',
  },
  // Стили для трех точек и модального окна действий
  eventActionsButton: {
    position: 'absolute',
    bottom: 15,
    right: 15,
    width: 38,
    height: 38,
    borderRadius: 13,
    backgroundColor: 'rgba(20, 20, 24, 0.55)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 10,
    padding: 8,
    ...(({
      backdropFilter: 'blur(14px)',
      WebkitBackdropFilter: 'blur(14px)',
    } as unknown) as object),
  },
  eventActionsButtonText: {
    fontSize: 18,
    color: 'rgba(244,244,245,0.8)',
    fontWeight: 'bold',
  },
  saveButton: {
    position: 'absolute',
    bottom: 12,
    right: 12,
    backgroundColor: '#FF8D32',
    borderRadius: 16,
    paddingHorizontal: 18,
    paddingVertical: 9,
    zIndex: 10,
    shadowColor: '#FF8D32',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 14,
    elevation: 6,
  },
  saveButtonText: {
    color: '#1a0d00',
    fontSize: 13.5,
    fontWeight: '700',
    letterSpacing: 0.1,
  },
  parameterWrapper: {
    position: 'relative',
  },
  parameterOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  parameterOverlayHidden: {
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
  },
  eyeIcon: {
    fontSize: 24,
  },
  titleContainer: {
    marginBottom: 8,
    backgroundColor: '#2a2a2a',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    alignSelf: 'flex-start',
  },
  titleWithPostsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  postsCount: {
    fontSize: 11,
    color: 'rgba(244,244,245,0.55)',
    fontStyle: 'italic',
  },
  hiddenElement: {
    display: 'none',
  },
  tagsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 8,
    marginBottom: 8,
  },
  tagsContainerOverlay: {
    position: 'absolute',
    top: 8,
    left: 8,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    zIndex: 10,
  },
  tagBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: 'rgba(10, 10, 12, 0.45)',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.22)',
    ...(({
      backdropFilter: 'blur(16px)',
      WebkitBackdropFilter: 'blur(16px)',
    } as unknown) as object),
  },
  tagText: {
    fontSize: 12,
    color: '#f4f4f5',
    fontWeight: '600',
    letterSpacing: 0.1,
  },
});

