-- AlterEnum
DO $$ BEGIN
    ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'EVENT_CANCELLED';
    ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'EVENT_UPDATED';
    ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'EVENT_PARTICIPANT_JOINED';
    ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'EVENT_PARTICIPANT_LEFT';
    ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'EVENT_POST_ADDED';
END $$;

