import { StyleSheet } from 'react-native';
import { Palette, Radius } from '../constants/DesignSystem';

/** Стили вынесены из app/calendar.tsx без изменений. */
export const calendarStyles = StyleSheet.create({
  // Кнопка возврата поверх календаря (оба режима — месяц и неделя)
  backButton: {
    position: 'absolute',
    top: Platform.OS === 'web' ? 16 : 56,
    left: 12,
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(20,20,24,0.72)',
    zIndex: 20,
  },
  container: {
    flex: 1,
    backgroundColor: '#0a0a0c',
    ...(Platform.OS === 'web' && ({
      height: '100vh',
      overflowY: 'auto',
      WebkitOverflowScrolling: 'touch',
    } as unknown as ViewStyle)),
  },
  previewCtaContainer: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 24,
  },
  previewCtaButton: {
    backgroundColor: '#34C759',
    height: 48,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
  },
  previewCtaText: {
    color: '#f4f4f5',
    fontSize: 16,
    fontWeight: '600',
  },
  weekHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 40,
    paddingHorizontal: 20,
    paddingBottom: 14,
  },
  weekMonthName: {
    color: '#f4f4f5',
    fontSize: 24,
    fontWeight: '700',
    letterSpacing: -0.4,
  },
  addEventButton: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: '#FF8D32',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#FF8D32',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.32,
    shadowRadius: 12,
  },
  addEventButtonText: {
    color: '#f4f4f5',
    fontSize: 28,
    fontWeight: 'bold',
  },
  weekContainer: {
    flexDirection: 'row',
    paddingTop: 5,
    paddingHorizontal: 10,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.07)',
  },
  weekDay: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 10,
    borderRadius: 12,
    marginHorizontal: 4,
    position: 'relative',
    minHeight: 90,
  },
  selectedWeekDayBright: {
    // Выбранный день без фона, но яркий
  },
  unselectedWeekDayDimmed: {
    // Невыбранные дни затемнены через оверлей (убрали, больше не используется)
  },
  dimmedText: {
    opacity: 0.5,
  },
  weekDayEventsContainer: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
    top: 35,
    left: 0,
    right: 0,
  },
  weekEventCircleContainer: {
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
  weekEventCircle: {
    width: 50,
    height: 50,
    borderRadius: 25,
    overflow: 'hidden',
  },
  weekPendingOverlay: {
    position: 'absolute',
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: 'rgba(0,0,0,0.35)',
  },
  weekCountBadge: {
    position: 'absolute',
    bottom: -2,
    right: -2,
    backgroundColor: '#FF3B30',
    borderRadius: 8,
    paddingHorizontal: 4,
    paddingVertical: 1,
    minWidth: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  weekCountText: {
    color: '#f4f4f5',
    fontSize: 8,
    fontWeight: 'bold',
  },
  weekDayName: {
    color: 'rgba(244,244,245,0.55)',
    fontSize: 12,
    position: 'absolute',
    top: 5,
    left: 0,
    right: 0,
    textAlign: 'center',
    zIndex: 10,
  },
  weekDayNumber: {
    color: '#f4f4f5',
    fontSize: 11,
    fontWeight: 'bold',
    textShadowColor: 'rgba(0, 0, 0, 0.75)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  weekDayNumberCentered: {
    position: 'absolute',
    top: 35,
    left: 0,
    right: 0,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 20,
  },
  weekDayNumberCenteredText: {
    color: '#f4f4f5',
    fontSize: 11,
    fontWeight: 'bold',
    textShadowColor: 'rgba(0, 0, 0, 0.75)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  dayView: {
    flex: 1,
    ...(Platform.OS === 'web' && {
      overflowY: 'auto' as any,
      maxHeight: '100%',
      WebkitOverflowScrolling: 'touch' as any,
    }),
  },
  hourSlot: {
    flexDirection: 'row',
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#1E1E1E',
  },
  hourLabel: {
    color: 'rgba(244,244,245,0.55)',
    fontSize: 14,
    width: 60,
    fontWeight: '600',
  },
  eventsContainer: {
    flex: 1,
  },
  eventItem: {
    backgroundColor: '#1E1E1E',
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
  },
  eventItemContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  eventTextContainer: {
    flex: 1,
  },
  previewEventItem: {
    borderWidth: 1,
    borderColor: '#FF8D32',
    backgroundColor: '#1B1236',
  },
  eventTitle: {
    color: '#f4f4f5',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  eventLocation: {
    color: 'rgba(244,244,245,0.55)',
    fontSize: 14,
  },
  placeholderText: {
    color: '#f4f4f5',
    fontSize: 18,
    textAlign: 'center',
    marginTop: 100,
  },
  // Стили для month view
  scrollView: {
    flex: 1,
  },
  monthContainer: {
    paddingHorizontal: 20,
    paddingVertical: 20,
    paddingBottom: 40,
    width: '100%',
    maxWidth: 500,
    alignSelf: 'center',
    ...(Platform.OS === 'web' ? ({ 
      boxSizing: 'border-box',
      margin: '0 auto',
    } as unknown as ViewStyle) : {}),
  },
  monthHeader: {
    marginBottom: 18,
    alignItems: 'center',
  },
  monthTitle: {
    fontSize: 26,
    fontWeight: '700',
    letterSpacing: -0.4,
    color: '#f4f4f5',
  },
  weekDaysHeader: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    marginBottom: 8,
    width: '100%',
    paddingHorizontal: 0,
  },
  weekDayHeaderCell: {
    alignItems: 'center',
    flexShrink: 0,
    minWidth: 0,
  },
  weekDayHeaderText: {
    color: 'rgba(244,244,245,0.4)',
    fontSize: 11.5,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  weekRow: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    marginBottom: 4,
    width: '100%',
    paddingHorizontal: 0,
  },
  dayCell: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 52,
    flexShrink: 0,
    minWidth: 0,
  },
  eventCircleContainer: {
    alignItems: 'center',
  },
  pastEventCircle: {
    opacity: 0.5,
  },
  eventPhotoCircle: {
    width: 42,
    height: 42,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: '#1c1c20',
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  dayNumberBadgeButton: {
    position: 'absolute',
    top: 4,
    right: 4,
    zIndex: 10,
  },
  dayNumberBadge: {
    color: '#f4f4f5',
    fontSize: 11,
    fontWeight: 'bold',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 10,
  },
  countBadge: {
    position: 'absolute',
    bottom: -2,
    right: -2,
    backgroundColor: '#FF3B30',
    borderRadius: 8,
    paddingHorizontal: 4,
    paddingVertical: 1,
    minWidth: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  countText: {
    color: '#f4f4f5',
    fontSize: 8,
    fontWeight: 'bold',
  },
  dayNumberCentered: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 20,
  },
  dayNumberCenteredText: {
    color: '#f4f4f5',
    fontSize: 11,
    fontWeight: 'bold',
    textShadowColor: 'rgba(0, 0, 0, 0.75)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  emptyDayNumber: {
    color: '#444444',
    fontSize: 14,
    fontWeight: '600',
  },
  // Наложение для имитации ч/б на pending события в месячной раскладке
  pendingBWOverlay: {
    position: 'absolute',
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: 'rgba(0,0,0,0.35)'
  },
  // Статус ожидания как в инбоксе (оранжевый бейдж)
  inboxStatusBadgePending: {
    backgroundColor: '#FF9500',
    width: 24,
    height: 24,
    borderRadius: 12,
    alignSelf: 'flex-start',
    marginTop: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  inboxStatusIcon: {
    color: '#f4f4f5',
    fontSize: 12,
    fontWeight: 'bold',
  },
  // Кнопка Подтвердить (обводка, светлый текст)
  confirmButton: {
    backgroundColor: 'transparent',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#f4f4f5',
  },
  confirmButtonText: {
    color: '#f4f4f5',
    fontSize: 14,
    fontWeight: '600',
  },
  // Модалка списка событий дня
  modalOverlayAbsolute: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dayEventsModal: {
    width: '90%',
    backgroundColor: '#141417',
    borderRadius: 16,
    padding: 16,
  },
  dayEventsTitle: {
    color: '#f4f4f5',
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 12,
  },
  dayEventRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
  },
  dayEventThumb: {
    width: 50,
    height: 50,
    borderRadius: 25,
    marginRight: 12,
    overflow: 'hidden',
  },
  dayEventTitle: {
    color: '#f4f4f5',
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 2,
  },
  dayEventMeta: {
    color: 'rgba(244,244,245,0.55)',
    fontSize: 12,
  },
  closeModalBtn: {
    marginTop: 12,
    alignSelf: 'flex-end',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  closeModalText: {
    color: '#f4f4f5',
    fontSize: 14,
  },
});
