import { StyleSheet } from 'react-native';

// Файл стилей; префикс _ исключает его из маршрутов Expo Router (не показывается в таб-баре)
export const createEventStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0a0a0c',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 60,
    paddingHorizontal: 20,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.07)',
  },
  backButton: {
    fontSize: 16,
    color: '#FF8D32',
    fontWeight: '600',
    marginRight: 15,
  },
  title: {
    fontSize: 20,
    fontWeight: '700',
    letterSpacing: -0.3,
    color: '#f4f4f5',
  },
  progressContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: '#0a0a0c',
    paddingTop: 60,
  },
  progressStep: {
    alignItems: 'center',
    flex: 1,
  },
  progressCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'transparent',
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.14)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 6,
  },
  progressCircleActive: {
    backgroundColor: '#FF8D32',
    borderColor: '#FF8D32',
  },
  progressNumber: {
    fontSize: 13,
    fontWeight: '700',
    color: 'rgba(244,244,245,0.45)',
  },
  progressNumberActive: {
    color: '#1a0d00',
  },
  progressTitle: {
    fontSize: 9,
    color: 'rgba(244,244,245,0.45)',
    textAlign: 'center',
  },
  progressTitleActive: {
    color: '#FF8D32',
    fontWeight: '600',
  },
  content: {
    flex: 1,
  },
  contentPreview: {
    flex: 1,
    backgroundColor: '#141417',
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 40,
  },
  stepContent: {
    flex: 1,
  },
  previewWrapper: {
    flex: 1,
    backgroundColor: '#0a0a0c',
  },
  previewScrollView: {
    flex: 1,
    backgroundColor: '#0a0a0c',
  },
  previewScrollContent: {
    paddingHorizontal: 0, // Убираем padding - он будет в EventCard
    paddingTop: 0,
    paddingBottom: 100,
    flexGrow: 1,
  },
  previewCardContainer: {
    width: '100%',
    paddingHorizontal: 12, // Отступы как в ленте
  },
  previewEmptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  previewEmptyText: {
    fontSize: 14,
    color: 'rgba(244,244,245,0.55)',
    textAlign: 'center',
  },
  previewNavigation: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    paddingBottom: 50, // Отступ снизу для таб-бара
    backgroundColor: '#0a0a0c',
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.07)',
  },
  stepTitle: {
    fontSize: 23,
    fontWeight: '700',
    letterSpacing: -0.4,
    color: '#f4f4f5',
    marginBottom: 24,
  },
  label: {
    fontSize: 11,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 1,
    color: 'rgba(244,244,245,0.32)',
    marginBottom: 8,
    marginTop: 18,
  },
  input: {
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 16,
    fontSize: 14.5,
    backgroundColor: 'rgba(255,255,255,0.045)',
    color: '#f4f4f5',
  },
  textArea: {
    height: 100,
    textAlignVertical: 'top',
  },
  radioGroup: {
    marginTop: 20,
  },
  radioOption: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    borderRadius: 16,
    marginBottom: 8,
    backgroundColor: 'rgba(255,255,255,0.045)',
  },
  radioSelected: {
    borderColor: '#FF8D32',
    backgroundColor: 'rgba(255,141,50,0.14)',
  },
  radioText: {
    fontSize: 16,
    color: '#f4f4f5',
  },
  previewCardWrapper: {
    position: 'relative',
    marginBottom: 0,
  },
  addMediaButton: {
    position: 'absolute',
    top: 80, // Центр места для фото (160px / 2 = 80px) - медиа-контейнер в EventCard имеет высоту 160px
    left: '50%',
    transform: [{ translateX: -22 }], // Центрирование по горизонтали (44px / 2 = 22px)
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#FF8D32',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  addMediaButtonText: {
    fontSize: 28,
    color: '#f4f4f5',
    fontWeight: '300',
  },
  removeMediaButton: {
    position: 'absolute',
    top: 10,
    left: 10,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  removeMediaButtonText: {
    fontSize: 18,
    color: '#f4f4f5',
    fontWeight: 'bold',
  },
  previewHint: {
    fontSize: 14,
    color: 'rgba(244,244,245,0.55)',
    marginBottom: 12,
    fontStyle: 'italic',
  },
  tagsSection: {
    marginTop: 20,
    padding: 16,
    backgroundColor: '#141417',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.07)',
  },
  tagsSectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#f4f4f5',
    marginBottom: 12,
  },
  tagsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  tagBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: 'rgba(26, 26, 26, 0.65)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.85)',
  },
  tagText: {
    fontSize: 14,
    color: '#f4f4f5',
    marginRight: 6,
  },
  removeTagButton: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#FF8D32',
    justifyContent: 'center',
    alignItems: 'center',
  },
  removeTagText: {
    fontSize: 12,
    color: '#f4f4f5',
    fontWeight: 'bold',
  },
  addTagButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,0.07)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
  },
  addTagButtonText: {
    fontSize: 20,
    color: '#f4f4f5',
    fontWeight: 'bold',
  },
  tagInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  tagInput: {
    flex: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#1c1c20',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    color: '#f4f4f5',
    fontSize: 14,
  },
  tagInputCancel: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#FF3B30',
    justifyContent: 'center',
    alignItems: 'center',
  },
  tagInputCancelText: {
    fontSize: 14,
    color: '#f4f4f5',
    fontWeight: 'bold',
  },
  navigation: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 0,
    paddingVertical: 20,
    marginTop: 30,
  },
  navigationPreview: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(26, 26, 26, 0.95)',
    paddingHorizontal: 20,
    paddingVertical: 20,
    marginTop: 0,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.07)',
  },
  backNavButton: {
    height: 50,
    paddingHorizontal: 24,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    backgroundColor: '#1c1c20',
    justifyContent: 'center',
    alignItems: 'center',
  },
  backNavText: {
    fontSize: 14.5,
    color: '#f4f4f5',
    fontWeight: '600',
  },
  nextButton: {
    flex: 1,
    height: 50,
    marginLeft: 12,
    backgroundColor: '#FF8D32',
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#FF8D32',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.32,
    shadowRadius: 16,
  },
  nextButtonText: {
    fontSize: 14.5,
    color: '#1a0d00',
    fontWeight: '600',
  },
  submitButton: {
    flex: 1,
    height: 50,
    marginLeft: 12,
    backgroundColor: '#FF8D32',
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#FF8D32',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.32,
    shadowRadius: 16,
  },
  submitButtonDisabled: {
    opacity: 0.5,
  },
  submitButtonText: {
    fontSize: 14.5,
    color: '#1a0d00',
    fontWeight: '700',
  },
  // Стили для работы с изображениями
  imageContainer: {
    position: 'relative',
    marginBottom: 16,
  },
  selectedImage: {
    width: '100%',
    height: 200,
    borderRadius: 12,
    resizeMode: 'cover',
  },
  removeImageButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    borderRadius: 15,
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  removeImageText: {
    color: '#f4f4f5',
    fontSize: 16,
    fontWeight: 'bold',
  },
  addPhotoButton: {
    backgroundColor: '#FF8D32',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 12,
  },
  addPhotoButtonText: {
    color: '#f4f4f5',
    fontSize: 16,
    fontWeight: '600',
  },
  addImageButton: {
    height: 170,
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.14)',
    borderStyle: 'dashed',
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    marginBottom: 16,
    backgroundColor: 'transparent',
  },
  addImageIcon: {
    fontSize: 26,
    marginBottom: 0,
  },
  addImageText: {
    fontSize: 13,
    color: 'rgba(244,244,245,0.55)',
    fontWeight: '500',
  },
  imageHint: {
    fontSize: 14,
    color: 'rgba(244,244,245,0.55)',
    marginBottom: 8,
    fontStyle: 'italic',
  },
  previewImageContainer: {
    marginBottom: 16,
    borderRadius: 12,
    overflow: 'hidden',
  },
  previewImage: {
    width: '100%',
    height: 150,
    resizeMode: 'cover',
  },
  // Стили для селекторов даты и времени
  dateTimeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(255,255,255,0.045)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 16,
  },
  dateTimeButtonText: {
    fontSize: 16,
    color: '#f4f4f5',
    flex: 1,
  },
  dateTimeButtonIcon: {
    fontSize: 20,
    marginLeft: 12,
  },
  locationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  locationInput: {
    flex: 1,
    height: 50,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.07)',
    borderRadius: 8,
    paddingHorizontal: 15,
    fontSize: 16,
    color: '#f4f4f5',
    backgroundColor: '#141417',
  },
  locationButtons: {
    flexDirection: 'row',
    marginLeft: 10,
    gap: 10,
  },
  locationButton: {
    width: 50,
    height: 50,
    backgroundColor: '#141417',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.07)',
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  locationButtonActive: {
    backgroundColor: 'rgba(255,141,50,0.14)',
    borderColor: '#FF8D32',
  },
  suggestionsContainer: {
    marginTop: 5,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.07)',
    borderRadius: 8,
    backgroundColor: '#141417',
    maxHeight: 200,
    overflow: 'hidden',
  },
  suggestionItem: {
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.07)',
  },
  suggestionName: {
    color: '#f4f4f5',
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 4,
  },
  suggestionDescription: {
    color: 'rgba(244,244,245,0.55)',
    fontSize: 12,
  },
  locationButtonText: {
    fontSize: 20,
  },
  autocompleteContainer: {
    flex: 1,
  },
  autocompleteInput: {
    height: 50,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    borderRadius: 12,
    paddingHorizontal: 16,
    fontSize: 16,
    backgroundColor: '#f4f4f5',
    color: '#1A1A1A',
  },
  autocompleteList: {
    position: 'absolute',
    top: 60,
    left: 0,
    right: 0,
    backgroundColor: '#f4f4f5',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    maxHeight: 200,
    zIndex: 1000,
  },
  pickerContainer: {
    marginBottom: 16,
  },
  confirmButton: {
    backgroundColor: '#FF8D32',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 12,
  },
  confirmButtonText: {
    color: '#f4f4f5',
    fontSize: 16,
    fontWeight: '600',
  },
  // Стили для нового шага "Участники"
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#f4f4f5',
    marginTop: 32,
    marginBottom: 16,
  },
  ageRestrictionContainer: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 0,
  },
  ageInputContainer: {
    flex: 1,
  },
  ageLabel: {
    fontSize: 12,
    color: 'rgba(244,244,245,0.45)',
    marginBottom: 6,
  },
  ageInput: {
    flex: 1,
    marginTop: 0,
  },
  checkboxGroup: {
    marginTop: 4,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
  },
  checkboxRow: {
    marginTop: 8,
    marginBottom: 8,
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  checkboxOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 16,
    marginRight: 8,
    marginBottom: 4,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  checkboxOptionActive: {
    backgroundColor: 'rgba(255,141,50,0.12)',
    borderColor: '#FF8D32',
  },
  tooltipButton: {
    marginLeft: 6,
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  tooltipIcon: {
    fontSize: 16,
    color: 'rgba(244,244,245,0.45)',
  },
  tooltipContainer: {
    backgroundColor: '#141417',
    padding: 12,
    borderRadius: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.07)',
  },
  tooltipText: {
    color: 'rgba(244,244,245,0.7)',
    fontSize: 13,
    lineHeight: 19,
  },
  checkboxText: {
    fontSize: 14.5,
    fontWeight: '500',
    color: 'rgba(244,244,245,0.75)',
  },
  checkboxTextActive: {
    color: '#FF8D32',
    fontWeight: '600',
  },
  recurringContainer: {
    marginTop: 12,
    marginBottom: 16,
  },
  recurringOption: {
    padding: 14,
    marginBottom: 10,
    backgroundColor: '#141417',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.07)',
  },
  recurringOptionActive: {
    backgroundColor: 'rgba(255,141,50,0.14)',
    borderColor: '#FF8D32',
  },
  recurringOptionText: {
    fontSize: 16,
    color: '#f4f4f5',
  },
  selectedRecurringText: {
    fontSize: 14,
    color: '#FF8D32',
    marginTop: 8,
    fontStyle: 'italic',
  },
  calendarContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 12,
    gap: 8,
  },
  calendarDay: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#141417',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.07)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  calendarDaySelected: {
    backgroundColor: '#FF8D32',
    borderColor: '#FF8D32',
  },
  calendarDayText: {
    fontSize: 14,
    color: '#f4f4f5',
  },
  calendarDayTextSelected: {
    color: '#f4f4f5',
    fontWeight: 'bold',
  },
  // Стили для полноценного календаря
  calendarMonthContainer: {
    marginBottom: 32,
  },
  calendarMonthHeader: {
    paddingVertical: 16,
    paddingHorizontal: 20,
    alignItems: 'center',
  },
  calendarMonthTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#f4f4f5',
  },
  calendarWeekDaysHeader: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    marginBottom: 8,
  },
  calendarWeekDayHeaderCell: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
  },
  calendarWeekDayHeaderText: {
    fontSize: 12,
    color: 'rgba(244,244,245,0.55)',
    fontWeight: '600',
  },
  calendarWeekRow: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    marginBottom: 4,
  },
  calendarDayCell: {
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    marginHorizontal: 2,
  },
  calendarDayCellSelected: {
    backgroundColor: '#FF8D32',
  },
  calendarDayCellText: {
    fontSize: 16,
    color: '#f4f4f5',
  },
  calendarDayCellTextSelected: {
    color: '#f4f4f5',
    fontWeight: 'bold',
  },
  modalFriendItemSelected: {
    backgroundColor: 'rgba(255,141,50,0.14)',
  },
  modalHint: {
    fontSize: 14,
    color: 'rgba(244,244,245,0.55)',
    marginBottom: 12,
    textAlign: 'center',
  },
  inviteContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  addButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#FF8D32',
    borderRadius: 8,
  },
  addButtonText: {
    color: '#f4f4f5',
    fontSize: 18,
    fontWeight: 'bold',
  },
  invitedAvatarsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 12,
    gap: 8,
  },
  invitedAvatarContainer: {
    position: 'relative',
  },
  invitedAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#FF8D32',
  },
  removeInvitedButton: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: '#FF3B30',
    borderRadius: 10,
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  removeInvitedText: {
    color: '#f4f4f5',
    fontSize: 12,
    fontWeight: 'bold',
  },
  excludedAvatarsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 12,
    gap: 8,
  },
  excludedAvatarContainer: {
    position: 'relative',
  },
  excludedAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#FF3B30',
  },
  removeExcludedButton: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: '#FF3B30',
    borderRadius: 8,
    width: 16,
    height: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  removeExcludedText: {
    color: '#f4f4f5',
    fontSize: 10,
    fontWeight: 'bold',
  },
  targetingContainer: {
    marginTop: 16,
    padding: 16,
    backgroundColor: '#141417',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#FF8D32',
  },
  targetingPriceContainer: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#2a2a2a',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  targetingPriceLabel: {
    fontSize: 16,
    color: 'rgba(244,244,245,0.55)',
    fontWeight: '500',
  },
  targetingPrice: {
    fontSize: 20,
    color: '#FF8D32',
    fontWeight: '700',
  },
  // Стили для модальных окон
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#141417',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 20,
    paddingBottom: 40,
    paddingHorizontal: 20,
    maxHeight: '80%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#f4f4f5',
  },
  modalCloseButton: {
    fontSize: 24,
    color: '#f4f4f5',
    fontWeight: 'bold',
  },
  modalSearchInput: {
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.07)',
    borderRadius: 12,
    padding: 12,
    fontSize: 16,
    backgroundColor: 'rgba(255,255,255,0.05)',
    color: '#f4f4f5',
    marginBottom: 16,
  },
  modalScrollView: {
    maxHeight: 400,
  },
  modalFriendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.07)',
  },
  modalFriendAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 12,
  },
  modalFriendInfo: {
    flex: 1,
  },
  modalFriendName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#f4f4f5',
  },
  modalFriendUsername: {
    fontSize: 14,
    color: 'rgba(244,244,245,0.55)',
    marginTop: 2,
  },
  modalCheckbox: {
    fontSize: 20,
    color: '#f4f4f5',
  },
  modalConfirmButton: {
    backgroundColor: '#FF8D32',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    marginTop: 16,
  },
  modalConfirmButtonDisabled: {
    backgroundColor: 'rgba(255,255,255,0.07)',
    opacity: 0.5,
  },
  modalConfirmButtonText: {
    color: '#f4f4f5',
    fontSize: 16,
    fontWeight: 'bold',
  },
});
