import { StyleSheet } from 'react-native';

// Не маршрут: файл стилей, но expo-router требует default export для любых файлов в app/
export default function EventProfileStylesPlaceholder() {
  return null;
}

export const eventProfileStyles = StyleSheet.create({
  absoluteFill: StyleSheet.absoluteFillObject,
  container: {
    flex: 1,
    backgroundColor: '#0a0a0c',
  },
  backButtonFixed: {
    position: 'absolute',
    top: 60,
    left: 20,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    borderRadius: 20,
  },
  backText: {
    color: '#f4f4f5',
    fontSize: 24,
  },
  editButtonFixed: {
    position: 'absolute',
    top: 60,
    right: 20,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    borderRadius: 20,
  },
  editIcon: {
    fontSize: 20,
  },
  content: {
    flex: 1,
  },
  eventInfo: {
    paddingHorizontal: 20,
    paddingTop: 8, // Такое же расстояние как в карточке события (contentContainer paddingTop: 8)
    paddingBottom: 20,
    position: 'relative',
  },
  eventAvatarContainer: {
    width: '100%',
    height: 220,
    marginBottom: 0,
    borderRadius: 0,
    overflow: 'hidden',
    position: 'relative',
  },
  eventAvatar: {
    width: '100%',
    height: '100%',
    borderRadius: 0,
  },
  changePhotoButton: {
    position: 'absolute',
    bottom: 10,
    right: 10,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
  },
  changePhotoButtonText: {
    color: '#f4f4f5',
    fontSize: 14,
    fontWeight: '600',
  },
  eventName: {
    color: '#f4f4f5',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 6,
  },
  eventDescription: {
    color: '#CCC',
    fontSize: 14,
    lineHeight: 18,
    marginBottom: 8,
  },
  parametersContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 8,
  },
  parameterItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1c1c20',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    marginRight: 6,
    marginBottom: 4,
  },
  parameterEmoji: {
    fontSize: 12,
    marginRight: 4,
  },
  parameterText: {
    fontSize: 12,
    color: '#DDD',
    fontWeight: '500',
  },
  participantsParameterItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1c1c20',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    marginRight: 6,
    marginBottom: 4,
  },
  participantsMiniAvatars: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 6,
  },
  participantMiniAvatar: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
  },
  participantMoreMini: {
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  participantMoreMiniText: {
    color: '#f4f4f5',
    fontSize: 8,
    fontWeight: 'bold',
  },
  participantsCountText: {
    fontSize: 12,
    color: '#DDD',
    fontWeight: '500',
  },
  divider: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 16,
    marginHorizontal: 16,
    gap: 10,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  addContentButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
    backgroundColor: 'rgba(255,255,255,0.04)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  addContentIcon: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: 18,
    fontWeight: '400',
  },
  chatButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
    backgroundColor: 'rgba(255,255,255,0.04)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  eventActionsButton: {
    position: 'absolute',
    bottom: 15,
    right: 15,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 4,
    elevation: 10,
  },
  eventActionsButtonText: {
    color: '#f4f4f5',
    fontSize: 20,
    fontWeight: 'bold',
    lineHeight: 20,
  },
  actionsModalHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignSelf: 'center',
    marginTop: 12,
    marginBottom: 4,
  },
  actionsModalCloseBtn: {
    width: 30,
    height: 30,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.07)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  actionsModalContainer: {
    backgroundColor: '#18181e',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderWidth: 1,
    borderBottomWidth: 0,
    borderColor: 'rgba(255,255,255,0.08)',
    maxHeight: '75%',
    paddingBottom: 32,
    width: '100%',
    maxWidth: 500,
  },
  actionsModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 22,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.07)',
  },
  actionsModalTitle: {
    color: '#f4f4f5',
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: -0.2,
  },
  actionsModalClose: {
    color: 'rgba(244,244,245,0.5)',
    fontSize: 16,
  },
  actionsModalScroll: {
    paddingHorizontal: 14,
    paddingTop: 8,
  },
  actionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 8,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.05)',
    gap: 14,
  },
  actionItemLast: {
    borderBottomWidth: 0,
  },
  actionItemText: {
    flex: 1,
    color: '#f4f4f5',
    fontSize: 15.5,
    fontWeight: '500',
    letterSpacing: -0.1,
  },
  actionItemTextDisabled: {
    color: 'rgba(244,244,245,0.28)',
  },
  saveButton: {
    position: 'absolute',
    bottom: 12,
    right: 12,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#FF8D32',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 4,
    elevation: 10,
  },
  saveButtonText: {
    color: '#f4f4f5',
    fontSize: 14,
    fontWeight: '600',
  },
  parameterWrapper: {
    position: 'relative',
  },
  parameterOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
  },
  parameterOverlayHidden: {
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
  },
  eyeIcon: {
    fontSize: 24,
  },
  editField: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    color: '#f4f4f5',
    paddingHorizontal: 15,
    paddingVertical: 12,
    borderRadius: 12,
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 6,
    borderWidth: 1,
    borderColor: '#444',
  },
  editFieldDescription: {
    fontWeight: 'normal',
    minHeight: 60,
    textAlignVertical: 'top',
  },
  parameterTextInput: {
    fontSize: 12,
    color: '#DDD',
    fontWeight: '500',
    flex: 1,
    padding: 0,
    margin: 0,
  },
  postsSection: {
    paddingHorizontal: 0, // Нет отступов от краев
    width: '100%',
  },
  postsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    alignContent: 'flex-start',
    alignItems: 'flex-start',
  },
  postItem: {
    marginBottom: 0,
    overflow: 'hidden',
    flexShrink: 0,
    flexGrow: 0,
    flexBasis: 'auto',
    // boxSizing: 'border-box' не поддерживается в React Native, используем другой подход
  },
  postItemWithRightDivider: {
    borderRightWidth: 1,
    borderRightColor: 'rgba(255,255,255,0.07)',
  },
  postImage: {
    width: '100%',
    borderRadius: 0,
  },
  postTextContainer: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: 0,
    padding: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  postText: {
    color: '#f4f4f5',
    fontSize: 12,
    textAlign: 'center',
  },
  musicCard: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: 0,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    overflow: 'hidden',
  },
  musicCoverImageFull: {
    width: '100%',
    height: '100%',
  },
  musicPlaceholder: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#1c1c20',
  },
  playingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  playingIcon: {
    fontSize: 24,
  },
  playButtonOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
  },
  playIconOverlay: {
    fontSize: 24,
  },
  emptyPosts: {
    paddingVertical: 40,
    alignItems: 'center',
  },
  emptyPostsText: {
    color: 'rgba(244,244,245,0.55)',
    fontSize: 16,
    fontStyle: 'italic',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.65)',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#18181e',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderWidth: 1,
    borderBottomWidth: 0,
    borderColor: 'rgba(255,255,255,0.08)',
    padding: 22,
    paddingBottom: 36,
    maxHeight: '85%',
    width: '100%',
    maxWidth: 500,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.07)',
  },
  modalTitle: {
    color: '#f4f4f5',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: -0.2,
    flex: 1,
  },
  closeButton: {
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.07)',
  },
  closeButtonText: {
    color: 'rgba(244,244,245,0.5)',
    fontSize: 16,
    fontWeight: 'bold',
    lineHeight: 20,
  },
  editInput: {
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.09)',
    color: '#f4f4f5',
    paddingHorizontal: 14,
    paddingVertical: 13,
    borderRadius: 14,
    fontSize: 15,
    marginBottom: 12,
  },
  editTextArea: {
    height: 100,
    textAlignVertical: 'top',
    paddingTop: 13,
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
    marginTop: 4,
  },
  cancelButton: {
    flex: 1,
    paddingVertical: 14,
    alignItems: 'center',
    borderRadius: 15,
    backgroundColor: 'rgba(255,255,255,0.07)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.09)',
  },
  cancelButtonText: {
    color: 'rgba(244,244,245,0.7)',
    fontSize: 15,
    fontWeight: '600',
  },
  errorText: {
    color: '#f4f4f5',
    fontSize: 16,
    textAlign: 'center',
    marginTop: 100,
  },
  // Стили для музыки (старые - удалены, используются новые выше)
  musicIcon: {
    fontSize: 32,
  },
  // Стили для модального окна добавления контента
  contentTypeButtons: {
    flexDirection: 'row',
    gap: 10,
    marginVertical: 20,
    paddingHorizontal: 4,
  },
  contentTypeButton: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 22,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    borderRadius: 18,
  },
  contentTypeIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: 'rgba(255,141,50,0.12)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  contentTypeText: {
    color: '#f4f4f5',
    fontSize: 13.5,
    fontWeight: '600',
  },
  demoLabel: {
    color: 'rgba(255,141,50,0.6)',
    fontSize: 11,
    fontWeight: '500',
    textAlign: 'center',
    marginBottom: 10,
    letterSpacing: 0.5,
  },
  // Стили для поиска треков
  searchResults: {
    maxHeight: 200,
    marginVertical: 10,
  },
  searchResultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    backgroundColor: '#444',
    borderRadius: 8,
    marginBottom: 5,
  },
  searchResultImage: {
    width: 50,
    height: 50,
    borderRadius: 8,
    marginRight: 12,
  },
  searchResultInfo: {
    flex: 1,
  },
  searchResultTitle: {
    color: '#f4f4f5',
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 4,
  },
  searchResultArtist: {
    color: 'rgba(244,244,245,0.55)',
    fontSize: 14,
  },
  loadingContainer: {
    padding: 20,
    alignItems: 'center',
  },
  loadingText: {
    color: 'rgba(244,244,245,0.55)',
    fontSize: 16,
  },
  selectedTrackContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: 12,
    marginVertical: 10,
  },
  selectedTrackImage: {
    width: 60,
    height: 60,
    borderRadius: 8,
    marginRight: 15,
  },
  selectedTrackInfo: {
    flex: 1,
  },
  selectedTrackTitle: {
    color: '#f4f4f5',
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  selectedTrackArtist: {
    color: 'rgba(244,244,245,0.55)',
    fontSize: 16,
  },
  // Стили для ленты контента
  contentFeedContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#0a0a0c',
    zIndex: 1000,
  },
  backToProfileButton: {
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 10,
  },
  backToProfileText: {
    color: '#FF8D32',
    fontSize: 16,
    fontWeight: '600',
  },
  contentFeedScroll: {
    flex: 1,
  },
  contentFeedContent: {
    paddingBottom: 100,
    paddingTop: 8,
  },
  fullPostCard: {
    marginBottom: 20,
    backgroundColor: '#141417',
    borderRadius: 12,
    overflow: 'hidden',
  },
  fullPostImage: {
    width: '100%',
    height: 400,
  },
  fullMusicCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 20,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  fullMusicCover: {
    width: 80,
    height: 80,
    backgroundColor: '#555',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 20,
  },
  fullMusicIcon: {
    fontSize: 32,
  },
  fullMusicInfo: {
    flex: 1,
  },
  fullMusicTitle: {
    color: '#f4f4f5',
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  fullMusicArtist: {
    color: 'rgba(244,244,245,0.55)',
    fontSize: 16,
  },
  fullPlayButton: {
    width: 60,
    height: 60,
    backgroundColor: '#FF8D32',
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxContainer: {
    marginVertical: 15,
    paddingVertical: 10,
  },
  checkbox: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  checkboxBox: {
    width: 24,
    height: 24,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.12)',
    borderRadius: 4,
    marginRight: 10,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  checkboxBoxChecked: {
    backgroundColor: '#FF8D32',
    borderColor: '#FF8D32',
  },
  checkboxCheckmark: {
    color: '#f4f4f5',
    fontSize: 16,
    fontWeight: 'bold',
  },
  checkboxLabel: {
    color: '#f4f4f5',
    fontSize: 16,
  },
  photoCaptionsContainer: {
    marginVertical: 10,
  },
  photoCaptionRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 15,
  },
  photoNumberBadge: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#FF8D32',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    marginTop: 8,
  },
  photoNumberText: {
    color: '#f4f4f5',
    fontSize: 14,
    fontWeight: 'bold',
  },
  photoCaptionInput: {
    flex: 1,
    minHeight: 60,
  },
  fullPlayIcon: {
    fontSize: 24,
  },
  fullPostTextContainer: {
    padding: 20,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  fullPostText: {
    color: '#f4f4f5',
  },
  imageModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.95)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fullImage: {
    width: '100%',
    height: '100%',
  },
  imageModalCloseButton: {
    position: 'absolute',
    top: 60,
    right: 20,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  imageModalCloseText: {
    color: '#f4f4f5',
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 24,
  },
  fullPostAuthor: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    backgroundColor: '#1c1c20',
  },
  fullAuthorAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 12,
  },
  fullAuthorInfo: {
    flex: 1,
  },
  fullAuthorUsername: {
    color: '#f4f4f5',
    fontSize: 16,
    fontWeight: '600',
  },
  fullPostDate: {
    color: 'rgba(244,244,245,0.55)',
    fontSize: 14,
    marginTop: 2,
  },
  fullPostCaption: {
    color: '#f4f4f5',
    fontSize: 16,
    lineHeight: 24,
    padding: 15,
    backgroundColor: '#1c1c20',
  },
  // Стили для модального окна передачи роли организатора
  shareModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.65)',
    justifyContent: 'flex-end',
  },
  shareModalContent: {
    backgroundColor: '#18181e',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderWidth: 1,
    borderBottomWidth: 0,
    borderColor: 'rgba(255,255,255,0.08)',
    paddingTop: 0,
    paddingBottom: 36,
    paddingHorizontal: 0,
    maxHeight: '80%',
  },
  shareModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 22,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.07)',
    marginTop: 4,
  },
  shareModalTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#f4f4f5',
    letterSpacing: -0.2,
  },
  shareModalCloseButton: {
    fontSize: 16,
    color: 'rgba(244,244,245,0.5)',
    fontWeight: 'bold',
  },
  transferOrganizerDescription: {
    color: 'rgba(244,244,245,0.55)',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 16,
    paddingHorizontal: 20,
    paddingTop: 12,
  },
  emptyParticipantsContainer: {
    padding: 40,
    alignItems: 'center',
  },
  emptyParticipantsText: {
    color: 'rgba(244,244,245,0.32)',
    fontSize: 14,
  },
  shareModalList: {
    paddingHorizontal: 14,
    paddingTop: 8,
    maxHeight: 400,
  },
  shareModalItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.05)',
    gap: 12,
  },
  shareModalItemSelected: {
    backgroundColor: 'rgba(255,141,50,0.07)',
    borderRadius: 12,
  },
  shareModalAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#1c1c20',
  },
  shareModalItemInfo: {
    flex: 1,
  },
  shareModalItemName: {
    fontSize: 15,
    fontWeight: '600',
    color: '#f4f4f5',
    letterSpacing: -0.1,
  },
  shareModalItemSubtext: {
    fontSize: 13,
    color: 'rgba(244,244,245,0.5)',
    marginTop: 2,
  },
  shareModalCheckbox: {
    width: 24,
    height: 24,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.2)',
    backgroundColor: 'rgba(255,255,255,0.04)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  shareModalCheckboxText: {
    fontSize: 14,
    color: '#f4f4f5',
  },
  shareModalSendButton: {
    backgroundColor: '#FF8D32',
    borderRadius: 15,
    paddingVertical: 15,
    alignItems: 'center',
    marginTop: 14,
    marginHorizontal: 16,
  },
  shareModalSendButtonDisabled: {
    opacity: 0.4,
  },
  shareModalSendButtonText: {
    color: '#f4f4f5',
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: -0.1,
  },
  cancelEventButton: {
    backgroundColor: '#FF3B30',
    marginBottom: 12,
  },
});

