import { StyleSheet } from 'react-native';

export const eventProfileStyles = StyleSheet.create({
  absoluteFill: StyleSheet.absoluteFillObject,
  container: {
    flex: 1,
    backgroundColor: '#121212',
  },
  backButtonFixed: {
    position: 'absolute',
    top: 60,
    left: 20,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    borderRadius: 20,
  },
  backText: {
    color: '#FFF',
    fontSize: 24,
  },
  editButtonFixed: {
    position: 'absolute',
    top: 60,
    right: 20,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    borderRadius: 20,
  },
  editIcon: {
    fontSize: 20,
  },
  content: {
    flex: 1,
  },
  eventInfo: {
    paddingHorizontal: 20,
    paddingTop: 8, // Такое же расстояние как в карточке события (contentContainer paddingTop: 8)
    paddingBottom: 20,
    position: 'relative',
  },
  eventAvatarContainer: {
    width: '100%',
    marginBottom: 0, // Убрали marginBottom, чтобы расстояние было как в карточке (только paddingTop: 8)
    borderRadius: 0,
    overflow: 'hidden',
    position: 'relative',
  },
  eventAvatar: {
    width: '100%',
    height: '100%', // Занимает всю высоту контейнера, как в карточке (mediaImageVertical)
    borderRadius: 0,
    resizeMode: 'cover', // Как в карточке события (mediaImageVertical)
  },
  changePhotoButton: {
    position: 'absolute',
    bottom: 10,
    right: 10,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
  },
  changePhotoButtonText: {
    color: '#FFF',
    fontSize: 14,
    fontWeight: '600',
  },
  eventName: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 6,
  },
  eventDescription: {
    color: '#CCC',
    fontSize: 14,
    lineHeight: 18,
    marginBottom: 8,
  },
  parametersContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 8,
  },
  parameterItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2a2a2a',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    marginRight: 6,
    marginBottom: 4,
  },
  parameterEmoji: {
    fontSize: 12,
    marginRight: 4,
  },
  parameterText: {
    fontSize: 12,
    color: '#DDD',
    fontWeight: '500',
  },
  participantsParameterItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2a2a2a',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    marginRight: 6,
    marginBottom: 4,
  },
  participantsMiniAvatars: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 6,
  },
  participantMiniAvatar: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: '#FFFFFF',
  },
  participantMoreMini: {
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  participantMoreMiniText: {
    color: '#FFFFFF',
    fontSize: 8,
    fontWeight: 'bold',
  },
  participantsCountText: {
    fontSize: 12,
    color: '#DDD',
    fontWeight: '500',
  },
  divider: {
    height: 1,
    backgroundColor: '#333',
    marginVertical: 20,
    marginHorizontal: 20,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  addContentButton: {
    position: 'absolute',
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#007AFF',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  addContentIcon: {
    color: '#FFF',
    fontSize: 20,
    fontWeight: '300',
  },
  eventActionsButton: {
    position: 'absolute',
    bottom: 15,
    right: 15,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 4,
    elevation: 10,
  },
  eventActionsButtonText: {
    color: '#FFF',
    fontSize: 20,
    fontWeight: 'bold',
    lineHeight: 20,
  },
  actionsModalContainer: {
    backgroundColor: '#1A1A1A',
    borderRadius: 16,
    width: '85%',
    maxHeight: '70%',
    alignSelf: 'center',
  },
  actionsModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
  },
  actionsModalTitle: {
    color: '#FFF',
    fontSize: 20,
    fontWeight: 'bold',
  },
  actionsModalClose: {
    color: '#999',
    fontSize: 24,
    fontWeight: 'bold',
  },
  actionsModalScroll: {
    maxHeight: 400,
  },
  actionItem: {
    padding: 18,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
  },
  actionItemLast: {
    borderBottomWidth: 0,
  },
  actionItemText: {
    color: '#FFF',
    fontSize: 16,
  },
  actionItemTextDisabled: {
    color: '#666',
  },
  saveButton: {
    position: 'absolute',
    bottom: 12,
    right: 12,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#007AFF',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 4,
    elevation: 10,
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  parameterWrapper: {
    position: 'relative',
  },
  parameterOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
  },
  parameterOverlayHidden: {
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
  },
  eyeIcon: {
    fontSize: 24,
  },
  editField: {
    backgroundColor: '#333',
    color: '#FFF',
    paddingHorizontal: 15,
    paddingVertical: 12,
    borderRadius: 12,
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 6,
    borderWidth: 1,
    borderColor: '#444',
  },
  editFieldDescription: {
    fontWeight: 'normal',
    minHeight: 60,
    textAlignVertical: 'top',
  },
  parameterTextInput: {
    fontSize: 12,
    color: '#DDD',
    fontWeight: '500',
    flex: 1,
    padding: 0,
    margin: 0,
  },
  postsSection: {
    paddingHorizontal: 0, // Нет отступов от краев
  },
  postsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
  },
  postItem: {
    marginBottom: 0,
    overflow: 'hidden',
  },
  postItemWithRightDivider: {
    borderRightWidth: 1,
    borderRightColor: '#333',
  },
  postImage: {
    width: '100%',
    borderRadius: 0,
  },
  postTextContainer: {
    backgroundColor: '#333',
    borderRadius: 0,
    padding: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  postText: {
    color: '#FFF',
    fontSize: 12,
    textAlign: 'center',
  },
  musicCard: {
    backgroundColor: '#333',
    borderRadius: 0,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    overflow: 'hidden',
  },
  musicCoverImageFull: {
    width: '100%',
    height: '100%',
  },
  musicPlaceholder: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#2a2a2a',
  },
  playingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  playingIcon: {
    fontSize: 24,
  },
  playButtonOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
  },
  playIconOverlay: {
    fontSize: 24,
  },
  emptyPosts: {
    paddingVertical: 40,
    alignItems: 'center',
  },
  emptyPostsText: {
    color: '#999',
    fontSize: 16,
    fontStyle: 'italic',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#1A1A1A',
    borderRadius: 16,
    padding: 20,
    width: '90%',
    maxHeight: '80%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    color: '#FFF',
    fontSize: 20,
    fontWeight: 'bold',
    flex: 1,
    textAlign: 'center',
  },
  closeButton: {
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 16,
    backgroundColor: '#333',
  },
  closeButtonText: {
    color: '#FFF',
    fontSize: 20,
    fontWeight: 'bold',
    lineHeight: 20,
  },
  editInput: {
    backgroundColor: '#333',
    color: '#FFF',
    paddingHorizontal: 15,
    paddingVertical: 12,
    borderRadius: 8,
    fontSize: 16,
    marginBottom: 15,
  },
  editTextArea: {
    height: 100,
    textAlignVertical: 'top',
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  cancelButton: {
    flex: 1,
    paddingVertical: 12,
    alignItems: 'center',
    marginRight: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#666',
  },
  cancelButtonText: {
    color: '#999',
    fontSize: 16,
  },
  errorText: {
    color: '#FFF',
    fontSize: 16,
    textAlign: 'center',
    marginTop: 100,
  },
  // Стили для музыки (старые - удалены, используются новые выше)
  musicIcon: {
    fontSize: 32,
  },
  // Стили для модального окна добавления контента
  contentTypeButtons: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginVertical: 20,
  },
  contentTypeButton: {
    alignItems: 'center',
    padding: 20,
    backgroundColor: '#333',
    borderRadius: 12,
    minWidth: 100,
  },
  contentTypeIcon: {
    fontSize: 32,
    marginBottom: 10,
  },
  contentTypeText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: '600',
  },
  demoLabel: {
    color: '#FFA500',
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 8,
    backgroundColor: '#2A2A2A',
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 4,
  },
  // Стили для поиска треков
  searchResults: {
    maxHeight: 200,
    marginVertical: 10,
  },
  searchResultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    backgroundColor: '#444',
    borderRadius: 8,
    marginBottom: 5,
  },
  searchResultImage: {
    width: 50,
    height: 50,
    borderRadius: 8,
    marginRight: 12,
  },
  searchResultInfo: {
    flex: 1,
  },
  searchResultTitle: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 4,
  },
  searchResultArtist: {
    color: '#999',
    fontSize: 14,
  },
  loadingContainer: {
    padding: 20,
    alignItems: 'center',
  },
  loadingText: {
    color: '#999',
    fontSize: 16,
  },
  selectedTrackContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    backgroundColor: '#333',
    borderRadius: 12,
    marginVertical: 10,
  },
  selectedTrackImage: {
    width: 60,
    height: 60,
    borderRadius: 8,
    marginRight: 15,
  },
  selectedTrackInfo: {
    flex: 1,
  },
  selectedTrackTitle: {
    color: '#FFF',
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  selectedTrackArtist: {
    color: '#999',
    fontSize: 16,
  },
  // Стили для ленты контента
  contentFeedContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#121212',
    zIndex: 1000,
  },
  backToProfileButton: {
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 10,
  },
  backToProfileText: {
    color: '#007AFF',
    fontSize: 16,
    fontWeight: '600',
  },
  contentFeedScroll: {
    flex: 1,
  },
  contentFeedContent: {
    paddingBottom: 100,
    paddingTop: 8,
  },
  fullPostCard: {
    marginBottom: 20,
    backgroundColor: '#1A1A1A',
    borderRadius: 12,
    overflow: 'hidden',
  },
  fullPostImage: {
    width: '100%',
    height: 400,
  },
  fullMusicCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 20,
    backgroundColor: '#333',
  },
  fullMusicCover: {
    width: 80,
    height: 80,
    backgroundColor: '#555',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 20,
  },
  fullMusicIcon: {
    fontSize: 32,
  },
  fullMusicInfo: {
    flex: 1,
  },
  fullMusicTitle: {
    color: '#FFF',
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  fullMusicArtist: {
    color: '#999',
    fontSize: 16,
  },
  fullPlayButton: {
    width: 60,
    height: 60,
    backgroundColor: '#007AFF',
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxContainer: {
    marginVertical: 15,
    paddingVertical: 10,
  },
  checkbox: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  checkboxBox: {
    width: 24,
    height: 24,
    borderWidth: 2,
    borderColor: '#666',
    borderRadius: 4,
    marginRight: 10,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#333',
  },
  checkboxBoxChecked: {
    backgroundColor: '#8B5CF6',
    borderColor: '#8B5CF6',
  },
  checkboxCheckmark: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  checkboxLabel: {
    color: '#FFF',
    fontSize: 16,
  },
  photoCaptionsContainer: {
    marginVertical: 10,
  },
  photoCaptionRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 15,
  },
  photoNumberBadge: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#8B5CF6',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    marginTop: 8,
  },
  photoNumberText: {
    color: '#FFF',
    fontSize: 14,
    fontWeight: 'bold',
  },
  photoCaptionInput: {
    flex: 1,
    minHeight: 60,
  },
  fullPlayIcon: {
    fontSize: 24,
  },
  fullPostTextContainer: {
    padding: 20,
    backgroundColor: '#333',
  },
  fullPostText: {
    color: '#FFF',
  },
  imageModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.95)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fullImage: {
    width: '100%',
    height: '100%',
  },
  imageModalCloseButton: {
    position: 'absolute',
    top: 60,
    right: 20,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  imageModalCloseText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 24,
  },
  fullPostAuthor: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    backgroundColor: '#2A2A2A',
  },
  fullAuthorAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 12,
  },
  fullAuthorInfo: {
    flex: 1,
  },
  fullAuthorUsername: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: '600',
  },
  fullPostDate: {
    color: '#999',
    fontSize: 14,
    marginTop: 2,
  },
  fullPostCaption: {
    color: '#FFF',
    fontSize: 16,
    lineHeight: 24,
    padding: 15,
    backgroundColor: '#2A2A2A',
  },
});

